package ast

type Visitor interface {
	VisitIdentifier(*Ident)
	VisitBinaryExpr(*BinaryExpr)
	VisitDesignator(*Designator)
	VisitFuncCall(*FuncCall)
	VisitUnaryExpr(*UnaryExpr)
	VisitQualifiedIdent(*QualifiedIdent)
	VisitSet(*Set)
	VisitBasicLit(*BasicLit)
	VisitExprRange(*ExprRange)
	VisitDotOp(*DotOp)
	VisitIndexOp(*IndexOp)
	VisitTypeGuard(*TypeGuard)
	VisitPointerDeref(*PtrDref)

	VisitIfStmt(*IfStmt)
	VisitAssignStmt(*AssignStmt)
	VisitReturnStmt(*ReturnStmt)
	VisitProcCall(*ProcCall)
	VisitRepeatStmt(*RepeatStmt)
	VisitWhileStmt(*WhileStmt)
	VisitLoopStmt(*LoopStmt)
	VisitCaseStmt(*CaseStmt)
	VisitForStmt(*ForStmt)
	VisitExitStmt(*ExitStmt)
	VisitWithStmt(*WithStmt)

	VisitImport(*Import)
	VisitProcDecl(*ProcDecl)
	VisitVarDecl(*VarDecl)
	VisitConstDecl(*ConstDecl)
	VisitTypeDecl(*TypeDecl)
	VisitReceiver(*Receiver)
	VisitProcHead(*ProcHead)
	VisitProcBody(*ProcBody)
	VisitFPSection(*FPSection)
	VisitFormalParams(*FormalParams)

	VisitBasicType(*BasicType)
	VisitArrayType(*ArrayType)
	VisitPointerType(*PointerType)
	VisitProcType(*ProcType)
	VisitRecordType(*RecordType)
	VisitEnumType(*EnumType)
}
