package ast

type Visitor interface {
	VisitOberon(*OberonX) any
	VisitModule(*Module) any
	VisitMetaSection(*MetaSection) any
	VisitDefinition(*Definition) any
	VisitIdentifierDef(*IdentifierDef) any
	VisitBinaryExpr(*BinaryExpr) any
	VisitDesignator(*Designator) any
	VisitFunctionCall(*FunctionCall) any
	VisitUnaryExpr(*UnaryExpr) any
	VisitQualifiedIdent(*QualifiedIdent) any
	VisitSet(*Set) any
	VisitBasicLit(*BasicLit) any
	VisitExprRange(*ExprRange) any
	VisitNil(*Nil) any
	VisitIfStmt(*IfStmt) any
	VisitAssignmentStmt(*AssignmentStmt) any
	VisitReturnStmt(*ReturnStmt) any
	VisitProcedureCall(*ProcedureCall) any
	VisitRepeatStmt(*RepeatStmt) any
	VisitWhileStmt(*WhileStmt) any
	VisitLoopStmt(*LoopStmt) any
	VisitCaseStmt(*CaseStmt) any
	VisitForStmt(*ForStmt) any
	VisitExitStmt(*ExitStmt) any
	VisitWithStmt(*WithStmt) any
	VisitImport(*Import) any
	VisitProcedureDecl(*ProcedureDecl) any
	VisitVariableDecl(*VariableDecl) any
	VisitConstantDecl(*ConstantDecl) any
	VisitTypeDecl(*TypeDecl) any
	VisitProcedureHeading(*ProcedureHeading) any
	VisitProcedureBody(*ProcedureBody) any
	VisitBasicType(*BasicType) any
	VisitArrayType(*ArrayType) any
	VisitPointerType(*PointerType) any
	VisitProcedureType(*ProcedureType) any
	VisitRecordType(*RecordType) any
	VisitEnumType(*EnumType) any
	VisitNamedType(*NamedType) any
	VisitIndexOp(*IndexOp) any
	VisitPtrDeref(*PtrDeref) any
	VisitDotOp(*DotOp) any
	VisitTypeGuard(*TypeGuard) any
	VisitFieldList(*FieldList) any
	VisitLenList(*LenList) any
	VisitElseIfBranch(*ElseIfBranch) any
	VisitReceiver(*Receiver) any
	VisitFPSection(*FPSection) any
	VisitFormalParams(*FormalParams) any
	VisitCase(*Case) any
	VisitLabelRange(*LabelRange) any
	VisitGuard(*Guard) any
	VisitBadExpr(*BadExpr) any
	VisitBadDecl(*BadDecl) any
	VisitBadStmt(*BadStmt) any
	VisitBadType(*BadType) any
}
